CHANGELOG.md
Makefile
docs/validations.md
go.mod
go.sum
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/validator_test.go

resolves #2 
Adds new validation check to verify valid PromQL in rules annotation

feat: added new annotationIsValidPromQL check

---

CHANGELOG.md
docs/validations.md
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/validator_test.go

feat: add new validateAnnotationTemplates validator

---

CHANGELOG.md
docs/validations.md
go.mod
go.sum
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/validator_test.go

feat: add new validator expressionDoesNotUseIrate

---

CHANGELOG.md
docs/validations.md
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/validator_test.go

feat: add validator validFunctionsOnCounters

---

CHANGELOG.md
docs/validations.md
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/validator_test.go

feat: add validator rateBeforeAggregation

---

.github/workflows/go.yaml
.github/workflows/release.yaml
CHANGELOG.md
go.mod

feat: upgrade to go 1.18

---

.github/workflows/go.yaml
CHANGELOG.md
Makefile

feat: added e2e tests

---

.gitignore
CHANGELOG.md
Makefile
README.md
docs/validations.md
examples/rules.yaml
examples/validation.yaml
go.mod
go.sum
main.go
pkg/config/config.go
pkg/prometheus/cache.go
pkg/prometheus/mock.go
pkg/prometheus/prometheus.go
pkg/validate/validate.go
pkg/validator/alert.go
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/expression_helpers.go
pkg/validator/labels.go
pkg/validator/validator.go
pkg/validator/validator_test.go

All the things!

---

CHANGELOG.md
Makefile
README.md
examples/additional-validation.yaml
examples/rules.yaml
main.go
pkg/validate/validate.go

feat: allow multiple configs and thanos rules

---

CHANGELOG.md
docs/validations.md
pkg/prometheus/prometheus.go
pkg/validator/expression.go
pkg/validator/validator_test.go

fix:  and  validators

---

CHANGELOG.md
examples/rules.yaml
examples/validation.yaml
pkg/validator/expression.go

fix: unmarshall expressionDoesNotUseOlderDataThan

---

.gitignore
CHANGELOG.md
README.md
examples/rules/rules.yaml
examples/validation.yaml
main.go
pkg/config/config.go
pkg/report/report.go
pkg/validate/validate.go
pkg/validator/config.go

feat: allow to disable validations using comments

---

CHANGELOG.md
Makefile
examples/rules/rules_test.yaml
main.go
pkg/validate/validate.go

fix: logging

---

CHANGELOG.md
README.md
go.mod
go.sum
main.go
pkg/prometheus/mock.go
pkg/prometheus/prometheus.go
pkg/report/report.go
pkg/validate/validate.go
pkg/validator/alert.go
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/labels.go
pkg/validator/validator.go
pkg/validator/validator_test.go

feat: upgrade to go 1.19 and bump version in the go.mod

---

CHANGELOG.md
README.md
docs/validations.md
examples/human_readable.html
examples/human_readable.md
examples/validation.yaml
main.go
pkg/config/config.go
pkg/report/report.go
pkg/validate/validate.go
pkg/validator/annotations.go
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/expression_helpers.go
pkg/validator/expression_helpers_test.go
pkg/validator/group.go
pkg/validator/others.go

Needed for https://github.com/FUSAKLA/promruval/issues/45

Add support for validation of rule groups themselves

---

CHANGELOG.md
docs/validations.md
examples/human_readable.html
examples/human_readable.md
examples/rules/rules.yaml
examples/validation.yaml
main.go
pkg/validator/config.go
pkg/validator/group.go
pkg/validator/validator_test.go

closes https://github.com/FUSAKLA/promruval/issues/45

feat: add new validator hasAllowedEvaluationInterval

---

CHANGELOG.md
examples/rules/empty.yaml
main.go
pkg/validate/validate.go

fix: ignore empty rule files

---

CHANGELOG.md
docs/validations.md
examples/human_readable.html
examples/human_readable.md
examples/validation.yaml
pkg/unmarshaler/unmarshaler.go
pkg/validator/config.go
pkg/validator/group.go
pkg/validator/validator_test.go

feat: add new validator maxRulesPerGroup

---

CHANGELOG.md
docs/validations.md
examples/human_readable.html
examples/human_readable.md
examples/rules/rules.yaml
examples/validation.yaml
pkg/unmarshaler/unmarshaler.go
pkg/validator/config.go
pkg/validator/group.go
pkg/validator/validator_test.go

feat: add new validator hasAllowedLimit

---

CHANGELOG.md
docs/validations.md
examples/human_readable.html
examples/human_readable.md
examples/validation.yaml
pkg/validator/alert.go
pkg/validator/config.go
pkg/validator/validator_test.go

feat: add new validator keepFiringForIsNotLongerThan

---

CHANGELOG.md
docs/default_validation.yaml
docs/validations.md
pkg/validator/config.go
pkg/validator/expression.go
pkg/validator/validator_test.go

feat: add new validator expressionIsValidPromQL

---

CHANGELOG.md
README.md
docs/validations.md
main.go
pkg/config/config.go
pkg/prometheus/cache.go
pkg/prometheus/prometheus.go
pkg/validator/promql_expression.go

feat: add prometheus url and time created to the prometheus cache and invalidate on different prometheus url also

---

CHANGELOG.md
docs/validations.md
pkg/validator/alert.go
pkg/validator/config.go
pkg/validator/group.go
pkg/validator/recording_rule.go
pkg/validator/validator_test.go

feat: add new validators alertNameMatchesRegexp, groupNameMatchesRegexp, recordedMetricNameMatchesRegexp

---

CHANGELOG.md
go.mod
main.go
pkg/prometheus/prometheus.go
pkg/validate/validate.go
pkg/validator/promql_expression.go

feat: configure http headers for the promehteus client

---

CHANGELOG.md
docs/validations.md
examples/mimir/validation.yaml
pkg/validator/others.go
pkg/validator/util.go
pkg/validator/validator.go
pkg/validator/validator_test.go

feat: add negativeRegexp to hasSourceTenantsForMetrics

---

CHANGELOG.md
Makefile
README.md
examples/human_readable.html
examples/human_readable.md
examples/human_readable.txt
examples/rules/rules.yaml
examples/validation.yaml
main.go
pkg/config/config.go
pkg/report/report.go
pkg/report/validation.go
pkg/unmarshaler/unmarshaler.go
pkg/validate/validate.go
pkg/validationrule/validation_rule.go
pkg/validator/config.go
pkg/validator/config_test.go
pkg/validator/group.go
pkg/validator/labels.go
pkg/validator/recording_rule.go

Implements the idea from https://github.com/FUSAKLA/promruval/pull/101
But instead on the validator level it adds the conditions on the rule level, it is less invasive from the codebase perspective a makes bit more sense 
See the files in the `examples/` folder to see how it is used

feat: add onlyIf conditional rules

---

CHANGELOG.md
Makefile
pkg/report/indented_output.go
pkg/report/report.go
pkg/validate/validate.go
pkg/validationrule/validation_rule.go

fix: json and yaml marshaling of the validation output

---

.github/workflows/go.yaml
.github/workflows/release.yaml
.github/workflows/test-release.yaml
.golangci.yaml
CHANGELOG.md
go.mod
pkg/report/report.go
pkg/unmarshaler/unmarshaler.go

feat: bump go to 1.24.1
